### ISSUE TITLE
setting the editor to the monitor used

### ISSUE THREAD

**Issue by thebarto360** [sker65/go-dmd-clock#101]
![sugerencia thumb png c6526a9fa59743536cf5f2f39e946bef](https://user-images.githubusercontent.com/34549565/34004506-5896bfa2-e0f8-11e7-8e0b-e332aa45ede4.PNG)
I know that with + and with - the "dmd" is extended but you have to be using the scrollbars, I for example use a 24 "monitor and I have unused space in the right and down.

regards

**Comment by lucky01** [comment]
fixed with new layout
