### ISSUE TITLE
Not an issue but basic feature requests

### ISSUE THREAD

**Issue by 32assassin** [sker65/go-dmd-clock#103]
hello I like to start coloring some of my projects after using the editor. 
I feel like this basic features should be added in order to improve basic coloring.

1. Color Replacement tool  similar to what Pinball Browser has
Their are many scenes that can be redone with a single click.
when selecting the color replacement tool
https://www.dropbox.com/s/8jxs7n75gbsim4j/1.gif?dl=0

I would like to replace the green with white in this scene,  If the color replacement tool was available.
the each image in the scene could be updated with a single mouse click.

2. I'm not sure if the intent was to run this tool in window mode but on a 1080 monitor. their is allot of wasted space.  this would not be a problem if  I could re-size the DMD window.  If I zoom in on the DMD window  I'm no longer able to fit the entire DMD image in the DMD window.   I would like the ability to remove the DMD from the editor onto its own window so that I can stretch out the DMD window  to fit my monitor screen similar to this
https://www.dropbox.com/s/esb8hyrt1dlkltq/Capture.PNG?dl=0

where the red image is the DMD window.

3. Sample colors from images
 their are some scenes where I would like to use specific colors.  Colors found on BackGlass or PF images.

I would like a feature where I could import an image,  Not because I want to use it in a scene but simply to sample a color from it.  I'm currently importing an image into MS Paint sampling the colors and copying the RGB values into Pin2DMD,  This seems like a feature Pin2DMD should have in order to expedite coloring.

**Comment by lucky01** [comment]
1. can be done by swapping colors in the palette.
2. new layout has been implemented
3. pipette tool can now pick colors from 24bit color images (e.g gif imports)
