### ISSUE TITLE
Last/first frame of cut scene swap after color

### ISSUE THREAD

**Issue by tjc02002** [sker65/go-dmd-clock#107]
When I cut a scene it looks fine. I can color every frame in the scene and it seems to be fine until I color the last frame. After the last frame is colored, the editor is copying the colored last frame to the first frame replacing the first frame with the last(and erasing the correct first frame). Then it keeps an uncolored last frame on the scene, making it impossible to color the last frame(the color goes away after you click back or forward). This only started happening with the latest version of the editor which I downloaded on 3/10/2018.

**Comment by lucky01** [comment]
fixed
