### ISSUE TITLE
Null pointer exception when <Enter> is pressed after entering a palette name

### ISSUE THREAD

**Issue by djrobx** [sker65/go-dmd-clock#121]
I get a NullPointer Exception every time (Windows x64 v2.4.2.0)

Update: I found I can sometimes rename them, but it will always crash if I type anything in the list box (I had been trying to rename without hitting rename button).    Rename button doesn't work every time and sometimes also gives exception though.

**Comment by lucky01** [comment]
Can´t reproduce that crash either. Please make a more detailed explanation how to make it crash.

**Comment by djrobx** [comment]
On the version I have it will always crash with a null pointer exception if I try to type something in the palette combo box field and hit <enter>   (I had typed the "Xxxx" in this case)

<img width="596" alt="screen shot 2018-06-26 at 7 51 43 am" src="https://user-images.githubusercontent.com/1526865/41920611-edccc138-7915-11e8-96c7-f806bf69e03a.png">
