### ISSUE TITLE
Frame Delays above 999 are not visible

### ISSUE THREAD

**Issue by djrobx** [sker65/go-dmd-clock#122]
If I input, or load a recording that has a frame duration above 999, the UI stops updating the input box and the duration value cannot be seen.    

It's useful to have this as a large value sometimes to enable a color masking to continue until a different event.

**Comment by lucky01** [comment]
I can´t reproduce the problem with durations larger then 500

**Comment by djrobx** [comment]
For me changing the value of the duration on a frame is never saved.     Is there a trick to getting it to apply the change?     I don't know what the exact upper limit is but I've never seen anything over a 500.    Maybe try 1000.

**Comment by lucky01** [comment]
The duration field is only used for simple palette switches. If you want to edit the time a ColMask stays active edit the Delay field for the Colmask frame

**Comment by djrobx** [comment]
I think I managed to delays to stick, I may not have been pressing Enter.     However, I cannot see frame delays over 999.     I may want a color mask coloring to stick around longer than 1 second.
