### ISSUE TITLE
Error loading 128x16 projects

### ISSUE THREAD

**Issue by Rappelbox** [sker65/go-dmd-clock#125]
Once a project with 128x16 resolution is saved and reopenend none of the keyframes, palette switches etc. work. The editor opens the project with an error, editing is impossible. 

Masks have additional data inside, colorization export gives non-working files. 

As long as the project is started from scratch everything works as expected, exports too.

**Comment by djrobx** [comment]
His project XML seems to have generated one 128x32 mask for some reason.  If I edit that out of the XML and replace with a 128x16 one, it seems to work correctly from there.   Not sure how it got there in the first place though.

<img width="1680" alt="screen shot 2018-06-26 at 2 43 47 pm" src="https://user-images.githubusercontent.com/1526865/41988865-49cb7ce0-79f2-11e8-84ef-315a6aa70113.png">

**Comment by lucky01** [comment]
We use a 128x32 panels which is why all 128x16 projects are processed like 128x32. Don´t use the old 128x16 edit mode which was implemented for testing in an early stage.
