### ISSUE TITLE
Not an Issue more of a how to

### ISSUE THREAD

**Issue by 32assassin** [sker65/go-dmd-clock#126]
I colored World Poker tour English version on Pinball Browser,
you can find a color patch diff and a basic pal file for testing ( I do not have a license for Pinball Browser the PINMAME patch was not added)

Unfortunately;
 more than a handful of scenes where not colored by that program, and I had to do them in the PIN2DMD editor.  I was able to do allot of them but 
found more than a few animations that generate a different tag when ever they are displayed.
I can capture, cut, color and create a color scene switch.  but the tag that triggers the color scene will probably never trigger it.
I have a WIP project here
https://www.dropbox.com/sh/u50j99lfjtlivjb/AABS5ZZinGee4nCab54KKTDCa?dl=0

I have an Excel file that lists all the scenes with this problem.
the WIP editor project has a recording  (Full Play 2).  with multiple bookmarks (short cuts) to the scenes in question.   Each scene has the same animation but different tags;  I do not know how to get them to trigger my replacement scene.

also I have yet to see a project that implements the " Color Mask Sequence",   can you please update your youtube video  "Chapter 3"  using the latest editor.  When I try to use this technique  the masks change when I come back to the masked scene.

**Comment by lucky01** [comment]
You can only use replacement and palette switching mode for 16 color pinball machines like SAM. Using ColMask with these machines is not implemented because ColMask is meant to extend the number of colors of scenes which is normally 4 to 16. Since SAM machines already use 16 colors extending would mean that the editor should be able to handle 32 or 64 colors which is currently not supported. Using it anyway may lead to unpredictable results and is not recommended for future compatibility of your project.

**Comment by 32assassin** [comment]
I had a conversation with lucky about this, and thats the same thing he said.

I tried to use pallet switches ( unfortunatly they don't always trigger when the scene starts with dynamic content) and when they do
the duration is not working,  I cannot get the duration to save in the editor.
here is a video of me creating a pallet switch and adding the duration

https://www.dropbox.com/s/26801l58ogqcabx/capture-1.avi?dl=0

please let me know if I'm doing something wrong.


the thing is that in this project,  because I colored the scenes in Pinball Browser.
I do not have to do any coloring in Pin2DMD  (except one replacement scene)

I'm able to use ColMask sequences for any scene that starts WITHOUT any dynamic content.
the dynamic content will change even though I DID NOT use  a color mask in the scene.

the only problems I'm having is with scenes that start with dynamic content
they don't always trigger ( colmask or pallet trigger)
or 
if I use a pallet switch the duration is not working.


I have another major problem but I like to get the basics working before I move on.

**Comment by lucky01** [comment]
AFAIK you use Freezy´s DLL and it may be a problem which is specific to the DLL. I will check wether it is a problem of the editor or the DLL and report.

**Comment by 32assassin** [comment]
so I kinda figured out the problem with my missing triggers
I had this problem
https://www.dropbox.com/s/4fxo5u9g4kijl0y/capture-3.avi?dl=0

the spinning earth is made up of 11 individual frames,  I made a mask to remove the text and cut each frame from a non text frame. As you can see from the video the non text frames are working fine and SOME of the texted frames work.   As it turns out, even after using the mask on the same frame; using a single hash tag to trigger the same frame will not always work.  

So I  had the bright idea of creating a trigger for each tag found in each frame (4 triggers same frame).  and presto all the scenes are colored, I then tried  the same method on my non triggering scenes and they are all working now.  it seems like a complete waste or not the most efficient way of doing things, but I'm not about to play the table for 20 minutes to test each individual trigger just to figure out witch ones work and witch ones don't work.

Although this project seems to be an exercise on how NOT TO!!!!  use the editor
 I would say that this project is about 90% complete. I don't see why I can't get the missing scenes to work using the same method.

cut a full scene  --> create 4 colmask triggers  

I updated the pal and vni file link is on the first post
only the Spot the Tell sequence needs to be cut 
and Bumper Value needs to be checked as it cuts in the middle of the scene.
everything else should be working.
