### ISSUE TITLE
Pallet Import bug

### ISSUE THREAD

**Issue by 32assassin** [sker65/go-dmd-clock#131]
cab we get a fix for the pallet import

I have extracted pallets from other projects,  but when I import them to a new project 
they are overwriting my existing pallets

if I export a pallet in position 3 from one project
and import it to another project with an existing pallet at position 3
the new pallet will overwrite the existing #3 pallet.

I would like for the imported pallet to be assigned to a new open position or give me the option to assign it to any number I want.

**Comment by slippifishi** [comment]
Are you talking about the Save Palette / Load Palette actions? If so, then in the interim you can edit the xml and set the new index by hand - if you use an index that isn't used yet then it will take that number

**Comment by 32assassin** [comment]
thats what I was doing,  but it defeats the purpose of having an export/import feature,  another weird thing is that if you have 10 pallets used and you import a pallet with index 80, and then create a new pallet,  the new pallet will have index of 81. Index 11-79  will be skipped.

**Comment by lucky01** [comment]
fixed here
https://github.com/lucky01/go-dmd-clock/commit/a07810773e9c192fb8449c514fdc34e4b38accbc
- use next free index number for new palette
- add option append when importing palette data
