### ISSUE TITLE
Feature request: extra painting tool suggestions

### ISSUE THREAD

**Issue by slippifishi** [sker65/go-dmd-clock#137]
- Pixel palette replace tool
(For the purposes of this example, a palette is made up of 16 colours, held in 4 "indexes" of 4 colours)
Given I have a pixel which is currently using colour a from palette X index 0, let me replace ALL pixels in the scene using colour a from palette X index 0 with colour b from palette X index 2.
(This is not "use colour mask replacement to achieve it" this is "i want to replace all instances of the use of one colour in the scene with a different colour, in a single click, instead of clicking individual pixels"). I can provide a better example if needed.

- An adjustable size pencil/brush tool
For example, instead of painting one pixel at a time, paint a square of 2x2, or 3x3 or 4x4 etc...

- Dashed-line tool
Similar to the existing line tool, but instead of painting every pixel, paint every other pixel

**Comment by lucky01** [comment]
added toolSize spinner to layout with the following functions
- replace all pixels in the scene using selected colour if toolSize > 1
- set brushSize
- select dash size
