### ISSUE TITLE
Feature Request: Split scene to frames

### ISSUE THREAD

**Issue by slippifishi** [sker65/go-dmd-clock#142]
What it says; given a scene of say 15 frames, an action to split it into 15 individual frames. 

Ideally, make the # of frames per cut configurable, so instead of 15 individual frames, allow for 5 individual sequences of 3 frames each instead (for example). 

Prompt for a scene name prefix before splitting, then append the frame number onto the end of that prefix, eg mysplitframe 001, mysplitframe 002 etc

**Comment by slippifishi** [comment]
For clarity; the split frames should respect the source sequence - same palette, same scene type, same delay on each frame etc.

**Comment by lucky01** [comment]
added a split scene item to the scene menu in the latest version I just uploaded to google drive
