### ISSUE TITLE
Feature Request: Allow playback in realtime(!)

### ISSUE THREAD

**Issue by slippifishi** [sker65/go-dmd-clock#144]
Maybe this is already possible by juggling FSQ files onto the sdcard(!?!) but the ability to "playback" a dump and have the currently applied triggers in the project take effect during live preview on the DMD would be the ultimate testing tool. Even if this required an interim step to upload/export the project before the preview would work, it would undoubtedly speed the process.

**Comment by lucky01** [comment]
Did you try the upload project button in the file menu ?

**Comment by lucky01** [comment]
use "upload project" to generate and upload .pal and .fsq to a USB attached device.
