### ISSUE TITLE
Feature Request: Dot pitch adjustment

### ISSUE THREAD

**Issue by slippifishi** [sker65/go-dmd-clock#147]
This is perhaps more of a cosmetic feature idea, but I can think of times where it could be useful to adjust the dot pitch, or even switch it off completely. Consider the following three views:

![image](https://user-images.githubusercontent.com/3789754/72687705-7e17a280-3af8-11ea-8e18-7bd5880f1fb1.png)
This is approx the current view in the editor.

![image](https://user-images.githubusercontent.com/3789754/72687718-9e476180-3af8-11ea-869a-018b396e242f.png)
The is closer to what I actually see on the panel.

![image](https://user-images.githubusercontent.com/3789754/72687750-e070a300-3af8-11ea-99d5-1c59f4157944.png)
A solid view could be more appropriate when colouring, and approximates other image editors.

I could imagine a spinner/slider somewhere, though ideally it would be on the main form to allow fast switching between pitch settings.

**Comment by slippifishi** [comment]
Looking back at the screenshots (maybe it is my monitor!), but there is a noticeable difference between the bottom view (solid) and top view (current editor) - the "3d" part of the letters have been shaded a very dark shade of grey, but this is very hard to see in the top view, as the black surrounding the dot washes out the colour.

**Comment by lucky01** [comment]
https://github.com/lucky01/go-dmd-clock/commit/2fe1e53fb93c201c257707198b59adf67efd1e5a
