### ISSUE TITLE
Bug: maximum window width is too small

### ISSUE THREAD

**Issue by noflip95** [sker65/go-dmd-clock#148]
On Pin2DMD Editor2 (v2.5.0.6 build 271), the GUI on the main window is truncated on some PC.
The window can be resized (reduced) and moved (overide on right/left of the screen).
**But the maximum width is always limited to the screen size.**

On PC machine with screen size less than 1400 pixels, the GUI is truncated, and no way to access to the right missing part. On a portable PC, having 1366 x 768 screen, the right side of the GUI is truncated:
![2020-02-04_18h10_35](https://user-images.githubusercontent.com/60664538/73768766-e2ce3080-4779-11ea-8636-1080045f3872.png)

- the D-mask label is invisible
- the L-mask label is invisible
- The two checkboxes D-mask/L-mask are clickable, but are at the very right limit of the screen.
No way to adjust the windows size at more then 1366 pixels. 

There is no scrollbar to access the missing part on right side. The window can be moved to the left of the screen, but its width cannot be expanded more than the original windows size, thus making the right missing part, always hidden.

Thus, the editor is not usable with screens having less than 1400 pixels width.

**Comment by lucky01** [comment]
fixed in the latest beta build here https://drive.google.com/open?id=18wNl_JbPW4XbvLkJQbT_s_DhHZqwq9CI
