### ISSUE TITLE
Bug: inconsistent/outdated device modes

### ISSUE THREAD

**Issue by noflip95** [sker65/go-dmd-clock#149]
On Pin2DMD Editor2 (v2.5.0.6 build 271), the number of device modes is out of date.

The firmware Colorprism allow now (V3.08), up to 15 modes.
In menu Palettes/Modes - Configure Device via USB, **the drop list show only 7 modes.**

![2020-02-04_19h13_32](https://user-images.githubusercontent.com/60664538/73773816-28dbc200-4783-11ea-9db3-8ee271248e79.png)

Colorprism V3.08 modes:
![2020-02-04_19h16_42](https://user-images.githubusercontent.com/60664538/73773825-2b3e1c00-4783-11ea-8036-aebabe799b6a.png)

Selecting a mode in this droplist works, but activate a wrong mode.
Selecting "Gottlieb" in the list, cause the selection of "STERN SPIKE" on the Pin2DMD device.

**Comment by lucky01** [comment]
fixed in the latest beta build here https://drive.google.com/open?id=18wNl_JbPW4XbvLkJQbT_s_DhHZqwq9CI
