### ISSUE TITLE
 'mask' checkbox remain checked

### ISSUE THREAD

**Issue by comicalman** [sker65/go-dmd-clock#15]
Why when I go back and forth between keyframes, does the 'mask' checkbox disappear (for a frame I previously did check as a mask)?  This would be very helpful to see it selected AND the masked area on the DMD- upon return to frame.

**Comment by sker65** [comment]
Resolved in the latest version. mask is general not specific to a key frame. and additionally crc's are always matched with and w/o mask.

Won't fix.
