### ISSUE TITLE
Bug: Help/About window needs to be updated

### ISSUE THREAD

**Issue by noflip95** [sker65/go-dmd-clock#150]
Copyright 2018 is a bit... late.
The information's windows is too small and truncated.
![image](https://user-images.githubusercontent.com/60664538/73774915-211d1d00-4785-11ea-8877-193f5bf8a24f.png)

**Comment by lucky01** [comment]
fixed in the latest beta build here https://drive.google.com/open?id=18wNl_JbPW4XbvLkJQbT_s_DhHZqwq9CI
