### ISSUE TITLE
GUI issues: typos / entering duration manually doesn't work

### ISSUE THREAD

**Issue by noflip95** [sker65/go-dmd-clock#151]
![2020-02-14_08h11_02](https://user-images.githubusercontent.com/60664538/74509538-10e20c00-4f02-11ea-8990-b74032456b2c.png)

1) First a small typo, what are "Scences" ?
![2020-02-14_08h02_53](https://user-images.githubusercontent.com/60664538/74509604-3a9b3300-4f02-11ea-9f36-49807eeb34d4.png)
Sure, "**Scenes**" will be better here.

2) The entry in the duration zone does not work normally. The input direction appears reversed, as if the zone was defined for Arabic-Hebrew.
![2020-02-14_08h08_38](https://user-images.githubusercontent.com/60664538/74510352-de391300-4f03-11ea-9477-67259061ae33.png)
Not only is the direction reversed, it is also impossible to enter intermediate zeros. The cursor also does not move correctly, it remains at the start of the zone when typing.
- Typing "1234" will result as "4321"
- Typing "506" will result as "65"

**Comment by lucky01** [comment]
fixed here https://github.com/lucky01/go-dmd-clock/commit/e9e07c554fceb08c1d3559d5bced8e7831cc2f65
Use fetch duration function to set a duration for a desired length
