### ISSUE TITLE
'unknown' keyframe should return back to DEFAULT palette

### ISSUE THREAD

**Issue by comicalman** [sker65/go-dmd-clock#16]
Could you have any 'unknown' keyframe return back to DEFAULT palette?  Currently it seems if you don't specify a frame and its palette (and its duration)- it remains with the most recent palette....
  I DO see that this could be a BAD thing- it would require a duration for all keyframes. 

Perhaps somehow make this an option for the Project?

**Comment by sker65** [comment]
This is intentional. With key frames you have two options:
a) define a duration: palette will last as duration says
b) duration is 0: palette will stay until the next match.

Of course you can define as many key frames you like that return to default palette.

Wont fix
