### ISSUE TITLE
Feature Request: Select multiple keyframes together

### ISSUE THREAD

**Issue by Happymealtm** [sker65/go-dmd-clock#167]
Ability to hold a button say command and click on multiple keyframes in order to delete them all together instead of individually.
This can come in handy when you are working one someone else's old project and they have keyframes that are from an older method or are no longer needed. Sometimes there are many and deleting 1 by 1 takes time.

**Comment by lucky01** [comment]
added to the next build

**Comment by Happymealtm** [comment]
Thank you
