### ISSUE TITLE
Feature Request: Option checkbox in settings to auto load the last project upon reloading the editor after quit

### ISSUE THREAD

**Issue by Happymealtm** [sker65/go-dmd-clock#169]
It would be great to have a checkbox in settings to enable the auto loading of the last project you are working on. Sometimes people will work on the same project for a long time and this would save time when you reopen the application.

It would be similar to the load last save state dialog but instead it would open the project even if there wasn't a previous auto save.

**Comment by lucky01** [comment]
Saving my time by not implementing it
