### ISSUE TITLE
Feature Request: Typing a letter/key in the Scenes drop down box jumps to the first scene with that letter/key

### ISSUE THREAD

**Issue by Happymealtm** [sker65/go-dmd-clock#170]
Add the ability to type a letter in the scene drop down box and have the list jump to the first scene with that letter.

For example if you have 4 scenes names Art, Background, Black, Game Over and you selected the scene drop down menu and typed in the letter B it would jump to Background and select it.

**Comment by lucky01** [comment]
conflicting with editor shortcuts. Use the sort button on the scenes for better orientation
