### ISSUE TITLE
Bug: Pin2dmd editor v3.0.0.0 (2021-02-11) - drawing tool "color sampling" not working

### ISSUE THREAD

**Issue by Sprudeldudel** [sker65/go-dmd-clock#173]
When opening a scene in pin2dmd editor i cannot pick a color with the color sampling tool.

to reproduce:
1. open a colored scene
2. Select color picker tool by left click (pipette symbol)
3. go to color to pick in the image, leftclick it
4. nothing happens

To my understanding of the tool from other applications this process should result in the color from the image to be selected. however, this doesnt happen.

SCREENCAPTURE
https://user-images.githubusercontent.com/79440816/108823794-33047480-75c1-11eb-888e-db8cefd23c81.mp4

**Comment by lucky01** [comment]
The pipette tool is meant for and works only on 24bit colordepth scene imports. For lower colordepth scenes, use and copy the colors from the palette. Just tested it and works as expected
