### ISSUE TITLE
BUG: editor crashes (java freezes) upon deletion of keyframe. dumpfile attached

### ISSUE THREAD

**Issue by Sprudeldudel** [sker65/go-dmd-clock#188]
editor version 17.10.2021

[pin2dmd-editor6353598945795612534.zip](https://github.com/sker65/go-dmd-clock/files/7363342/pin2dmd-editor6353598945795612534.zip)

**Comment by lucky01** [comment]
All I can see from the log file that this is caused by livepreview beeing active and unable to update. Please turn of livepreview before editing your project. Most likely the java freeze can be stopped by disconnecting or resetting the pin2dmd device.
