### ISSUE TITLE
Editor immediately shuts down.

### ISSUE THREAD

**Issue by comicalman** [sker65/go-dmd-clock#19]
Trying to run the editor on my cab.  I can run on a laptop and desktop.  However, my Cab shows splash screen, then shutsdown.

Please provide a log so we can diagnose why this will not start up.

Note: I am running as admin and have unblocked.
Tried most recent version (from Apr 17 11AM CST).

**Comment by sker65** [comment]
have to check why no log file is written, the launch4j version (packed exe) maybe isnt capable to write logs
