### ISSUE TITLE
"Duplicate Palette" Warning every time project is loaded

### ISSUE THREAD

**Issue by rockdude233** [sker65/go-dmd-clock#190]
When you use a .gif file as an input for scenes and keyframes, the editor gives an unnecessary warning that a duplicate palette exists every time the project is restarted.

**Comment by lucky01** [comment]
I can´t reproduce that problem. Can you give me access to your project files ?

**Comment by Happymealtm** [comment]
Best way to reproduce this is to create 2 separate gifs that use the exact same palette and import them both so they show up as separate scenes. Then after saving your project, restart the editor.

**Comment by rockdude233** [comment]
The message can be avoided by changing palette colors of the gif-named palette.  Two gif-named palettes will exist in the palette list, but no warning message will be displayed during project load.
