### ISSUE TITLE
Editor issues with "Configure device via USB"

### ISSUE THREAD

**Issue by vitholiveira** [sker65/go-dmd-clock#64]
Hello,

I downloaded the editor and I tried to configure the device via USB.

I saw that, for instance, when you choose PinMame_Mono, the device changes to Bally/Williams! And when you change to WPC95 it changes to Gotllieb 92.

Thanks and regras,

Vitor

**Comment by lucky01** [comment]
Are you using the latest version from here 
https://bintray.com/sker65/pin2dmd/Editor/latest/view#files ?

**Comment by vitholiveira** [comment]
Hello Lucky,

is I am. 

My regards

Vitor

**Comment by lucky01** [comment]
fixed in version here https://drive.google.com/drive/folders/18wNl_JbPW4XbvLkJQbT_s_DhHZqwq9CI
