### ISSUE TITLE
Wrong Palette when clicking on Keyframe #51

### ISSUE THREAD

**Issue by lucky01** [sker65/go-dmd-clock#65]
Still happens when clicking around in the Keyframes list with Multiscene project

**Comment by lucky01** [comment]
I think this is related to the fact that you can change palette of a keyframe by simply changeing the palette
when the keyframe is selected. Maybe add a update button to assign changes to keyframes.

**Comment by sker65** [comment]
introduced new Apply button to avoid wrong assignments
