### ISSUE TITLE
Uhr bleibt nach einiger Zeit dunkel

### ISSUE THREAD

**Issue by eliottk** [sker65/go-dmd-clock#8]
Meine Uhr hat das Problem, dass sie nachdem sie sich ausgeschalten hat, da sich niemand im Raum befand und zappelte, sich hin und wieder nicht mehr einschaltet. Das ganze geht ein paar mal gut und dann bleibt sie dunkel. Ich muss dann einen Reset machen und dann geht sie wieder.

**Comment by sker65** [comment]
Leider das falsche Projekt

**Comment by sker65** [comment]
This issue was moved to sker65/goDMD#37
