### ISSUE TITLE
Auto duplicate palette check ?

### ISSUE THREAD

**Issue by lucky01** [sker65/go-dmd-clock#86]
Wenn ich eine Szene einer Palette zuordne, die so nochmal existiert, wird die mit dem niedrigeren Index genommen.
Kann das sein, dass Du da prüfst ob die gleiche Palette nochmal drin ist ?

**Comment by sker65** [comment]
kann ich nicht nachvollziehen. folgender test:
Szene mit palette wählen, palette kopieren, palette mit höherer nummer zu ordnen, szene hin und her schalten um zu sehen welche palette -> GEHT!

Vielleicht seit der generellen Umstellung der Paletten bzgl. des Pal löschen bugs
