### ISSUE TITLE
When exporting project (real pin) on OSX version, crashes on .fsq export

### ISSUE THREAD

**Issue by dethfactor** [sker65/go-dmd-clock#91]
When using the OSX version, when trying to export the project for a real pin it crashes after the "don't distribute alert" and it only outputs an fsq file that is 4-5 characters long. No palette is output.

**Comment by dethfactor** [comment]
The log stops at:

77939 [main] DEBUG ApplicationProperties - get prop oldexport = 'null'

**Comment by sker65** [comment]
this is not reproduceable. for my test project it works fine. I would recommend to test it with a simple fresh project. If this works, maybe the project data is corrupted.
This may can also be fixed, but I need the project data then.

**Comment by dethfactor** [comment]
I was able to reproduce with 2 different projects (1 complex, 1 relatively simple - 1 recording, 6 scenes, 2 keyframes) on two different mac laptops. Both export the output correctly on the Windows 32 version (win 8 - bootcamp) with the same source files.

**Comment by sker65** [comment]
Are you sure you have a license installed? Maybe it's license related. Of
course it should not crash, but maybe the problem is only present if there
is no license.

Am 11.09.2017 23:59 schrieb "dethfactor" <notifications@github.com>:

**Comment by dethfactor** [comment]
Yep. The liscense is installed. I wouldn't get the "rename the pal file to Pin2dmd.pal" dialog if the liscense wasn't installed. Nor would I get the save dialog. It seems to be crashing on the scene file generation as it outputs the pal file if I remove all the keyframes.

**Comment by sker65** [comment]
Is it possible for you to provide a sample project to demostrate the 
crash (dropbox link or google drive link)?

So it is easier to remove the bug.


Am 12.09.17 um 09:48 schrieb dethfactor:

**Comment by dethfactor** [comment]
I posted a google drive link of my current project a few replies back.
